name = 'Hugo Scriptless'
license = 'MIT'
licenselink = 'https://github.com/lewpar/hugo-scriptless/LICENSE'
description = 'JavaScript Free Hugo Theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/lewpar/hugo-scriptless'

# If the theme has a single author
[author]
  name = 'lewpar'
  homepage = 'https://cyberbilby.com/'
